name: Coding standard

on:
  push:
    paths:
      - '**.php'
      - '**.xml'
      - 'composer.*'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: coding-standard-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coding-standard:
    name: Coding standard
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: 8.4
          coverage: none

      - name: Install Composer dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0
        with:
          composer-options: '--no-scripts'

      - name: Apply Rector
        run: composer rector

      - name: Apply Coding Standard
        run: composer cs

      - name: Commit Fixes (if any)
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: 'style: apply coding standard'
