name: Ruleset validator

on:
  workflow_dispatch:
  pull_request:
    types: [ready_for_review]
  release:
    types: [published]

jobs:
  validator:
    name: Ruleset validator
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: 8.4
          coverage: none

      - name: Get Composer cache directory
        id: composer-cache
        run: |
          echo "composer_dir={$(composer config cache-files-dir)}" >> $GITHUB_OUTPUT

      - name: Retrieve Composer‘s cache
        uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6
        with:
          path: ${{ steps.composer-cache.outputs.composer_dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install composer dependencies
        run: "composer install --no-interaction --no-progress --no-scripts"

      - name: Validate ruleset
        uses: szepeviktor/phpcs-ruleset-validator@f07738521ac7d7dd31ccec1920022e6fae617bcb # v0.4.0
        with:
          xml_ruleset: IxDFCodingStandard/ruleset.xml
